# 项目资金支持配置
# 更多信息: https://help.github.com/en/articles/displaying-a-sponsor-button

# GitHub赞助
# github: [yourusername]

# 开源集合赞助平台
# open_collective: yuyuanwaf

# Ko-fi
# ko_fi: yuyuanwaf

# Tidelift
# tidelift: npm/yuyuanwaf

# 爱发电 (中国区)
# custom: ['https://afdian.net/@yuyuanwaf']

# PayPal
# custom: ['https://www.paypal.me/yuyuanwaf']

# 支付宝/微信
# custom: ['https://your-qrcode-url']

# 提示：取消注释并填写您的支付方式链接

